### ISSUE TITLE
Questions re: layout + general feedback

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/confectionery-website-prototype#1]
My first big project on Learn the Web! Very excited as I'm planning to create my portfolio with these projects!

Markbot is happy but I'm trying to improve the wireframe and would appreciate some advice/ feedback:

- Despite wonderful CSS layout cheat sheet, I'm having issues with centering elements on the page (placeholder boxes in this case). Wonder what I do wrong or not quite understand;

- I cannot get the navigation menu stretched across the page @38em. Thought it was due to inline vs block element situation and played with display values but didn't work;

- Any other suggestions to improve the wireframe?

@thomasjbradley - thank you so much!

**Comment by thomasjbradley** [comment]
It’s lookin’ good!

> @38em navigation

If you want to stretch the nav across there are two solutions I can think of:

1. Add `flex-basis` to `header li`: `flex-basis: 20%`
2. Switch from flex-box to CSS grid

---

> Centering

For the "seasonal collection" blocks you need `justify-content: center` on `.seasonal ul`

---

> Other improvements

- "Art for your taste buds" seems to be in the wrong place on larger screens
- The contact us footer segment could split to multiple columns on larger screens
- From a design view: I’m not sure I like the placement of the title & "view products" in the seasonal cards—they look mish-mash-y

**Comment by C-G-G** [comment]
Thanks for the feedback!

Centering, stretching the nav across and splitting the contact us footer segment are all good.

I agree with you on design (placement of title & view products in seasonal cards and even "Art for your taste buds"). I think I was just focusing more on applying new concepts/ skills I'm learning in Web Dev (rather than design). 

Not sure how they did it and whether it's good practice but I was going after what I saw on this site where the elements on boxes seem to be fixed and not move: https://cococochocolatiers.com/  

@thomasjbradley

**Comment by thomasjbradley** [comment]
> Not sure how they did it and whether it's good practice but I was going after what I saw on this site where the elements on boxes seem to be fixed and not move: https://cococochocolatiers.com/

Yeah, that’s perfectly good practice. And the way you’re doing it, with `position` is probably the best way to accomplish it.
